#!/bin/bash
set -ex

if [ "x${PDIV}" = 'xrelease' -o  "x${PDIV}" = 'x' ]
then
    PDIV=''
else
    PDIV="@${PDIV}"
fi

set +x

echo -e "\n\n******* Adding required spack repositories *******\n"
if [ -e ${SPACK_ROOT}/var/spack/repos/pdi ]
then
    spack repo rm ${SPACK_ROOT}/var/spack/repos/pdi &>/dev/null || true
fi
spack repo add "$(dirname "$(dirname "$0")")"

echo -e "\n\n******* Solve *******\n"
spack solve -I --reuse \
    "pdi${PDIV}" \
    "pdiplugin-decl-hdf5${PDIV}" \
    "pdiplugin-decl-netcdf${PDIV}" \
    "pdiplugin-mpi${PDIV}" \
    "pdiplugin-pycall${PDIV}" \
    "pdiplugin-serialize${PDIV}" \
    "pdiplugin-set-value${PDIV}" \
    "pdiplugin-trace${PDIV}" \
    "pdiplugin-user-code${PDIV}" \
    zpp


echo -e "\n\n******* Installation *******\n"
spack install --fail-fast --show-log-on-error --reuse \
    "pdi${PDIV}" \
    "pdiplugin-decl-hdf5${PDIV}" \
    "pdiplugin-decl-netcdf${PDIV}" \
    "pdiplugin-mpi${PDIV}" \
    "pdiplugin-pycall${PDIV}" \
    "pdiplugin-serialize${PDIV}" \
    "pdiplugin-set-value${PDIV}" \
    "pdiplugin-trace${PDIV}" \
    "pdiplugin-user-code${PDIV}" \
    zpp
