#!/bin/bash

cd "$(dirname "$0")"
cd ..

# version if not specified
VERSION="${VERSION:-latest}"
# compiler if not specified
COMPILER="${COMPILER:-gcc}"
# MPI implementation if not specified
MPI="${MPI:-openmpi}"
# libraries included if not specified
VARIANT="${VARIANT:-all}"
# version of pdi & plugins to install, develop if not specified
PDIV="${PDIV:-develop}"

echo "  ** You can set the following environment variables:"
echo "VERSION(oldest|latest)=${VERSION}"
echo "COMPILER(gcc|clang)=${COMPILER}"
echo "MPI(openmpi|mpich)=${MPI}"
echo "VARIANT(mini|all)=${VARIANT}"
echo "PDIV(develop|release|\$x.\$y.\$z)=${PDIV}"


SCRIPTDIR="$(mktemp --tmpdir -d pdi.spack.test.XXXXXX)"
SCRIPTDIR="${SCRIPTDIR}/scriptdir"
mkdir -p "${SCRIPTDIR}"

cat<<'EOF' > "${SCRIPTDIR}/spack_install_pdi.bash"
#!/bin/bash
set -ex

if [ "x${PDIV}" = 'xrelease' -o  "x${PDIV}" = 'x' ]
then
    PDIV=''
else
    PDIV="@${PDIV}"
fi

set +x

echo -e "\n\n******* Adding required spack repositories *******\n"
if [ -e ${SPACK_ROOT}/var/spack/repos/pdi ]
then
    spack repo rm ${SPACK_ROOT}/var/spack/repos/pdi &>/dev/null || true
fi
spack repo add /opt/spack-pdi

echo -e "\n\n******* Solve *******\n"
spack solve -NI --reuse \
    "pdi.paraconf${PDIV}" \
    "pdi.pdi${PDIV}" \
    "pdi.pdiplugin-decl-hdf5${PDIV}" \
    "pdi.pdiplugin-decl-netcdf${PDIV}" \
    "pdi.pdiplugin-mpi${PDIV}" \
    "pdi.pdiplugin-pycall${PDIV}" \
    "pdi.pdiplugin-serialize${PDIV}" \
    "pdi.pdiplugin-set-value${PDIV}" \
    "pdi.pdiplugin-trace${PDIV}" \
    "pdi.pdiplugin-user-code${PDIV}"


echo -e "\n\n******* Installation *******\n"
spack install --fail-fast --show-log-on-error --reuse \
    "pdi.paraconf${PDIV}" \
    "pdi.pdi${PDIV}" \
    "pdi.pdiplugin-decl-hdf5${PDIV}" \
    "pdi.pdiplugin-decl-netcdf${PDIV}" \
    "pdi.pdiplugin-mpi${PDIV}" \
    "pdi.pdiplugin-pycall${PDIV}" \
    "pdi.pdiplugin-serialize${PDIV}" \
    "pdi.pdiplugin-set-value${PDIV}" \
    "pdi.pdiplugin-trace${PDIV}" \
    "pdi.pdiplugin-user-code${PDIV}"
EOF

set -ex

docker run --rm \
    -v "${PWD}:/opt/spack-pdi:ro" \
    -v "${SCRIPTDIR}:/opt/scriptdir:ro" \
    --entrypoint spack-env \
    -e "PDIV=${PDIV}" \
    "ghcr.io/pdidev/fullspack/${VERSION}/${COMPILER}/${MPI}/${VARIANT}:v4" \
    "bash" "/opt/scriptdir/spack_install_pdi.bash"


rm -rf "${SCRIPTDIR}"
